[colors]
# Sfondo viola scuro (Unità-01 nocturn) e testo bianco luminoso
background=1a1025ff
text=f0f0f0ff

# Testo evidenziato e selezione (Viola elettrico e Verde terminale NERV)
match=39ff14ff
selection=7b2dbeff
selection-text=f0f0f0ff

# Bordo in arancione/rosso asimmetrico
border=ff4500ff

[border]
width=2
radius=12

[main]
font=JetBrainsMono Nerd Font:size=12
dpi-aware=auto
prompt=" "
icons-enabled=yes
lines=8
width=40
horizontal-pad=20
vertical-pad=15
inner-pad=10