[main]
font=JetBrainsMono Nerd Font:size=14
dpi-aware=auto
prompt="󰍉 "
placeholder="Cerca app, file o comandi..."
icons-enabled=yes
show-actions=no
lines=8
width=50
horizontal-pad=30
vertical-pad=25
inner-pad=15

[border]
width=2

[colors]
# Gruvbox Dark color scheme
background=110b0dff
text=ebdbb2ff
match=fe8019ff
selection=3c3836ff
selection-match=fabd2fff
selection-text=ebdbb2ff
border=504945ff

[dmenu]
mode=text
